version: "3"

services:
  cataloge_postgres:
    image: "postgres:14.0"
    ports:
      - "5439:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: cataloge_db
      POSTGRES_PASSWORD: cataloge_db_password
      POSTGRES_DB: cataloge_services
    volumes:
      - ./db-data/cataloge_postgres/:/var/lib/postgresql/data

  order_postgres:
    image: "postgres:14.0"
    ports:
      - "5440:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: order_db
      POSTGRES_PASSWORD: order_db_password
      POSTGRES_DB: order_services
    volumes:
      - ./db-data/order_postgres/:/var/lib/postgresql/data

  user_postgres:
    image: "postgres:14.0"
    ports:
      - "5441:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db_password
      POSTGRES_DB: user_services
    volumes:
      - ./db-data/user_postgres/:/var/lib/postgresql/data
